linters:
  BorderZero:
    enabled: false

  ColorVariable:
    enabled: false

  PropertySortOrder:
    enabled: false

  Comment:
    enabled: false

  StringQuotes:
    enabled: true
    style: "double_quotes"

  Compass::*:
    enabled: false

  NameFormat:
    convention: "BEM"

  NestingDepth:
    max_depth: 3

  PlaceholderInExtend:
    enabled: false

  Indentation:
    enabled: true
    width: 2

  HexLength:
    style: long

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
